language: android
jdk: oraclejdk7
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-21
    - extra-android-support
    - sys-img-armeabi-v7a-android-21
env:
  matrix:
    - ANDROID_SDKS=android-21 ANDROID_TARGET=android-21
before_script:
  - npm install -g grunt-cli
  - npm install
  - cd example
  - npm install
  - npm install ../
script: grunt
